// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: submarineswaprpc/submarineswap.proto

package submarineswaprpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSwapPaymentResponse_SwapError int32

const (
	GetSwapPaymentResponse_NO_ERROR                GetSwapPaymentResponse_SwapError = 0
	GetSwapPaymentResponse_FUNDS_EXCEED_LIMIT      GetSwapPaymentResponse_SwapError = 1
	GetSwapPaymentResponse_TX_TOO_SMALL            GetSwapPaymentResponse_SwapError = 2
	GetSwapPaymentResponse_INVOICE_AMOUNT_MISMATCH GetSwapPaymentResponse_SwapError = 3
	GetSwapPaymentResponse_SWAP_EXPIRED            GetSwapPaymentResponse_SwapError = 4
)

// Enum value maps for GetSwapPaymentResponse_SwapError.
var (
	GetSwapPaymentResponse_SwapError_name = map[int32]string{
		0: "NO_ERROR",
		1: "FUNDS_EXCEED_LIMIT",
		2: "TX_TOO_SMALL",
		3: "INVOICE_AMOUNT_MISMATCH",
		4: "SWAP_EXPIRED",
	}
	GetSwapPaymentResponse_SwapError_value = map[string]int32{
		"NO_ERROR":                0,
		"FUNDS_EXCEED_LIMIT":      1,
		"TX_TOO_SMALL":            2,
		"INVOICE_AMOUNT_MISMATCH": 3,
		"SWAP_EXPIRED":            4,
	}
)

func (x GetSwapPaymentResponse_SwapError) Enum() *GetSwapPaymentResponse_SwapError {
	p := new(GetSwapPaymentResponse_SwapError)
	*p = x
	return p
}

func (x GetSwapPaymentResponse_SwapError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetSwapPaymentResponse_SwapError) Descriptor() protoreflect.EnumDescriptor {
	return file_submarineswaprpc_submarineswap_proto_enumTypes[0].Descriptor()
}

func (GetSwapPaymentResponse_SwapError) Type() protoreflect.EnumType {
	return &file_submarineswaprpc_submarineswap_proto_enumTypes[0]
}

func (x GetSwapPaymentResponse_SwapError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetSwapPaymentResponse_SwapError.Descriptor instead.
func (GetSwapPaymentResponse_SwapError) EnumDescriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{5, 0}
}

type SubSwapServiceInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Pubkey []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *SubSwapServiceInitRequest) Reset() {
	*x = SubSwapServiceInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubSwapServiceInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubSwapServiceInitRequest) ProtoMessage() {}

func (x *SubSwapServiceInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubSwapServiceInitRequest.ProtoReflect.Descriptor instead.
func (*SubSwapServiceInitRequest) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{0}
}

func (x *SubSwapServiceInitRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *SubSwapServiceInitRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SubSwapServiceInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pubkey     []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	LockHeight int64  `protobuf:"varint,3,opt,name=lock_height,proto3" json:"lock_height,omitempty"`
}

func (x *SubSwapServiceInitResponse) Reset() {
	*x = SubSwapServiceInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubSwapServiceInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubSwapServiceInitResponse) ProtoMessage() {}

func (x *SubSwapServiceInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubSwapServiceInitResponse.ProtoReflect.Descriptor instead.
func (*SubSwapServiceInitResponse) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{1}
}

func (x *SubSwapServiceInitResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SubSwapServiceInitResponse) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SubSwapServiceInitResponse) GetLockHeight() int64 {
	if x != nil {
		return x.LockHeight
	}
	return 0
}

type UnspentAmountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// The address (to be used by a client using swap service)
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	/// The hash (to be used by a swapper service)
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *UnspentAmountRequest) Reset() {
	*x = UnspentAmountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnspentAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnspentAmountRequest) ProtoMessage() {}

func (x *UnspentAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnspentAmountRequest.ProtoReflect.Descriptor instead.
func (*UnspentAmountRequest) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{2}
}

func (x *UnspentAmountRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UnspentAmountRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type UnspentAmountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// The total amount
	Amount     int64                         `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	LockHeight int32                         `protobuf:"varint,2,opt,name=lock_height,proto3" json:"lock_height,omitempty"`
	Utxos      []*UnspentAmountResponse_Utxo `protobuf:"bytes,3,rep,name=utxos,proto3" json:"utxos,omitempty"`
}

func (x *UnspentAmountResponse) Reset() {
	*x = UnspentAmountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnspentAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnspentAmountResponse) ProtoMessage() {}

func (x *UnspentAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnspentAmountResponse.ProtoReflect.Descriptor instead.
func (*UnspentAmountResponse) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{3}
}

func (x *UnspentAmountResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UnspentAmountResponse) GetLockHeight() int32 {
	if x != nil {
		return x.LockHeight
	}
	return 0
}

func (x *UnspentAmountResponse) GetUtxos() []*UnspentAmountResponse_Utxo {
	if x != nil {
		return x.Utxos
	}
	return nil
}

type GetSwapPaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentRequest string `protobuf:"bytes,1,opt,name=paymentRequest,proto3" json:"paymentRequest,omitempty"`
	///redeem address
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetSwapPaymentRequest) Reset() {
	*x = GetSwapPaymentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapPaymentRequest) ProtoMessage() {}

func (x *GetSwapPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetSwapPaymentRequest) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{4}
}

func (x *GetSwapPaymentRequest) GetPaymentRequest() string {
	if x != nil {
		return x.PaymentRequest
	}
	return ""
}

func (x *GetSwapPaymentRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetSwapPaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PaymentError string `protobuf:"bytes,1,opt,name=paymentError,proto3" json:"paymentError,omitempty"`
	// deprecated
	FundsExceededLimit bool                             `protobuf:"varint,2,opt,name=funds_exceeded_limit,json=fundsExceededLimit,proto3" json:"funds_exceeded_limit,omitempty"`
	SwapError          GetSwapPaymentResponse_SwapError `protobuf:"varint,3,opt,name=swap_error,json=swapError,proto3,enum=main.GetSwapPaymentResponse_SwapError" json:"swap_error,omitempty"`
}

func (x *GetSwapPaymentResponse) Reset() {
	*x = GetSwapPaymentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSwapPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSwapPaymentResponse) ProtoMessage() {}

func (x *GetSwapPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSwapPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetSwapPaymentResponse) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{5}
}

func (x *GetSwapPaymentResponse) GetPaymentError() string {
	if x != nil {
		return x.PaymentError
	}
	return ""
}

func (x *GetSwapPaymentResponse) GetFundsExceededLimit() bool {
	if x != nil {
		return x.FundsExceededLimit
	}
	return false
}

func (x *GetSwapPaymentResponse) GetSwapError() GetSwapPaymentResponse_SwapError {
	if x != nil {
		return x.SwapError
	}
	return GetSwapPaymentResponse_NO_ERROR
}

type UnspentAmountResponse_Utxo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHeight int32  `protobuf:"varint,1,opt,name=block_height,proto3" json:"block_height,omitempty"`
	Amount      int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Txid        string `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	Index       uint32 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *UnspentAmountResponse_Utxo) Reset() {
	*x = UnspentAmountResponse_Utxo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnspentAmountResponse_Utxo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnspentAmountResponse_Utxo) ProtoMessage() {}

func (x *UnspentAmountResponse_Utxo) ProtoReflect() protoreflect.Message {
	mi := &file_submarineswaprpc_submarineswap_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnspentAmountResponse_Utxo.ProtoReflect.Descriptor instead.
func (*UnspentAmountResponse_Utxo) Descriptor() ([]byte, []int) {
	return file_submarineswaprpc_submarineswap_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UnspentAmountResponse_Utxo) GetBlockHeight() int32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *UnspentAmountResponse_Utxo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UnspentAmountResponse_Utxo) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *UnspentAmountResponse_Utxo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_submarineswaprpc_submarineswap_proto protoreflect.FileDescriptor

var file_submarineswaprpc_submarineswap_proto_rawDesc = []byte{
	0x0a, 0x24, 0x73, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x61, 0x70, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x61, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x47, 0x0a, 0x19,
	0x53, 0x75, 0x62, 0x53, 0x77, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x70, 0x0a, 0x1a, 0x53, 0x75, 0x62, 0x53, 0x77, 0x61, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x44, 0x0a, 0x14, 0x55, 0x6e, 0x73, 0x70, 0x65,
	0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0xf7, 0x01,
	0x0a, 0x15, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x36, 0x0a, 0x05, 0x75, 0x74, 0x78, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x74,
	0x78, 0x6f, 0x52, 0x05, 0x75, 0x74, 0x78, 0x6f, 0x73, 0x1a, 0x6c, 0x0a, 0x04, 0x55, 0x74, 0x78,
	0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x59, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x77,
	0x61, 0x70, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0xa9, 0x02, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x30, 0x0a, 0x14, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x5f, 0x65, 0x78, 0x63, 0x65, 0x65,
	0x64, 0x65, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x12, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x45, 0x0a, 0x0a, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x77, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x09, 0x73, 0x77, 0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x72, 0x0a, 0x09, 0x53, 0x77,
	0x61, 0x70, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x55, 0x4e, 0x44, 0x53, 0x5f, 0x45,
	0x58, 0x43, 0x45, 0x45, 0x44, 0x5f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x54, 0x58, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x12,
	0x1b, 0x0a, 0x17, 0x49, 0x4e, 0x56, 0x4f, 0x49, 0x43, 0x45, 0x5f, 0x41, 0x4d, 0x4f, 0x55, 0x4e,
	0x54, 0x5f, 0x4d, 0x49, 0x53, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x57, 0x41, 0x50, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x04, 0x32, 0x88,
	0x02, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x53, 0x77, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x12, 0x59, 0x0a, 0x12, 0x53, 0x75, 0x62, 0x53, 0x77, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x53, 0x75, 0x62, 0x53, 0x77, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x77, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a,
	0x0a, 0x0d, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x73,
	0x75, 0x62, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x65, 0x73, 0x77, 0x61, 0x70, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submarineswaprpc_submarineswap_proto_rawDescOnce sync.Once
	file_submarineswaprpc_submarineswap_proto_rawDescData = file_submarineswaprpc_submarineswap_proto_rawDesc
)

func file_submarineswaprpc_submarineswap_proto_rawDescGZIP() []byte {
	file_submarineswaprpc_submarineswap_proto_rawDescOnce.Do(func() {
		file_submarineswaprpc_submarineswap_proto_rawDescData = protoimpl.X.CompressGZIP(file_submarineswaprpc_submarineswap_proto_rawDescData)
	})
	return file_submarineswaprpc_submarineswap_proto_rawDescData
}

var file_submarineswaprpc_submarineswap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_submarineswaprpc_submarineswap_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_submarineswaprpc_submarineswap_proto_goTypes = []interface{}{
	(GetSwapPaymentResponse_SwapError)(0), // 0: main.GetSwapPaymentResponse.SwapError
	(*SubSwapServiceInitRequest)(nil),     // 1: main.SubSwapServiceInitRequest
	(*SubSwapServiceInitResponse)(nil),    // 2: main.SubSwapServiceInitResponse
	(*UnspentAmountRequest)(nil),          // 3: main.UnspentAmountRequest
	(*UnspentAmountResponse)(nil),         // 4: main.UnspentAmountResponse
	(*GetSwapPaymentRequest)(nil),         // 5: main.GetSwapPaymentRequest
	(*GetSwapPaymentResponse)(nil),        // 6: main.GetSwapPaymentResponse
	(*UnspentAmountResponse_Utxo)(nil),    // 7: main.UnspentAmountResponse.Utxo
}
var file_submarineswaprpc_submarineswap_proto_depIdxs = []int32{
	7, // 0: main.UnspentAmountResponse.utxos:type_name -> main.UnspentAmountResponse.Utxo
	0, // 1: main.GetSwapPaymentResponse.swap_error:type_name -> main.GetSwapPaymentResponse.SwapError
	1, // 2: main.SubmarineSwapper.SubSwapServiceInit:input_type -> main.SubSwapServiceInitRequest
	3, // 3: main.SubmarineSwapper.UnspentAmount:input_type -> main.UnspentAmountRequest
	5, // 4: main.SubmarineSwapper.GetSwapPayment:input_type -> main.GetSwapPaymentRequest
	2, // 5: main.SubmarineSwapper.SubSwapServiceInit:output_type -> main.SubSwapServiceInitResponse
	4, // 6: main.SubmarineSwapper.UnspentAmount:output_type -> main.UnspentAmountResponse
	6, // 7: main.SubmarineSwapper.GetSwapPayment:output_type -> main.GetSwapPaymentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_submarineswaprpc_submarineswap_proto_init() }
func file_submarineswaprpc_submarineswap_proto_init() {
	if File_submarineswaprpc_submarineswap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_submarineswaprpc_submarineswap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubSwapServiceInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubSwapServiceInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnspentAmountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnspentAmountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSwapPaymentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSwapPaymentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submarineswaprpc_submarineswap_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnspentAmountResponse_Utxo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submarineswaprpc_submarineswap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submarineswaprpc_submarineswap_proto_goTypes,
		DependencyIndexes: file_submarineswaprpc_submarineswap_proto_depIdxs,
		EnumInfos:         file_submarineswaprpc_submarineswap_proto_enumTypes,
		MessageInfos:      file_submarineswaprpc_submarineswap_proto_msgTypes,
	}.Build()
	File_submarineswaprpc_submarineswap_proto = out.File
	file_submarineswaprpc_submarineswap_proto_rawDesc = nil
	file_submarineswaprpc_submarineswap_proto_goTypes = nil
	file_submarineswaprpc_submarineswap_proto_depIdxs = nil
}
